### ISSUE TITLE
STM32 Unhandled workspace_loc variable in Touchgfx dual core projects

### ISSUE THREAD

**Issue by pkooiman** [microsoft/vscode-embedded-tools#34] opened 2023-01-30 09:46 UTC
When generating Touchgfx projects for dual core boards such as STM32H745i disco, the .cproject file for the CM7 processor contains include paths of the form

`<listOptionValue builtIn="false" value="&quot;${workspace_loc:/Drivers/BSP/Components/Common}&quot;"/>`

These end up in st-project,cmake as `"$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:ASM>>:${PROJECT_SOURCE_DIR}/build\\${workspace_loc:\\Drivers\\BSP\\Components\\Common}>"`
which is a syntax error.

Now, it is not clear why the STM tools add the include path, it seems completely unnecessary as the .cproject also contains the include path
`"../../../Drivers/BSP/Components/Common"/>`
which is the same. I delete the offending lines from st-project.cmake and everything works, but after every modification in Touchgfx they show up again which quickly gets old ;-)

Generating the "Blank UI" example for STM32H745i disco and importing `STM32CubeIDE\CM7\.cproject` into VS Code reproduces the error. There is no problem with single core boards, only dual core ones.

**Comment by benmcmorran** [comment] 2023-02-02 00:33
Thanks for the report! I can reproduce this issue. We can't easily fix this in the general case, because the ST project import feature has no knowledge of which directory was the workspace root in STM32CubeIDE. That said, I am updating the importer to drop paths that contain Eclipse macros we don't know how to interpret, which should fix the syntax errors you're getting. I'll let you know when this fix is available in the public pre-release channel.

Also note that if you need to add or remove include paths that weren't correctly handled by ST project import, you can add additional CMake logic to CMakeLists.txt and it will not be overwritten when the `.cproject` file changes. This doesn't help when there are synatx errors in `st-project.cmake`, but with those fixed it should be a viable workaround.

**Comment by benmcmorran** [comment] 2023-02-07 16:58
This issue is fixed in pre-release version `0.5.230207001` of the Embedded Tools. You can switch to the pre-release version (which updates nightly) in the VS Code Marketplace. Note that as discussed above, this change does not actually add full support for general `${workspace_loc}` macros, but does remove all unknown Eclipse macros.

![screenshot](https://user-images.githubusercontent.com/6981284/210019479-b5a7c09b-1ed5-4fd4-a251-bae5aaab040a.png)

**Comment by benmcmorran** [comment] 2023-02-09 21:14
This change is in version 0.6.0 of the extension, which is now available in the VS Code Marketplace.

**Closed as completed by benmcmorran** 2023-02-09 21:14 UTC
Labels: bug, fixed-pending-release
