### ISSUE TITLE
Importing ST project into VS Code

### ISSUE THREAD

**Issue by RaysoftTechnologiesInc** [microsoft/vscode-embedded-tools#24] opened 2022-09-27 06:35 UTC
I am trying to import my ST project into VS Code, I have followed all the steps in the blog I saw on Facebook, however I am getting that error when I run the debug command
![image](https://user-images.githubusercontent.com/45296244/192449841-52ee00b4-8bb9-410d-9725-62f065fed018.png)
I am not entirely sure what the issue is, but I am hoping that you can give me some pointers. My code is building successfully in CubeIDE
[cproject.zip](https://github.com/microsoft/vscode-embedded-tools/files/9652320/cproject.zip)
[st-project.zip](https://github.com/microsoft/vscode-embedded-tools/files/9652321/st-project.zip)
I have attached my cmake file and also my cproject file.

**Comment by benmcmorran** [comment] 2022-09-28 16:09
Thanks for the report! Based on your uploads, I was able to reproduce this issue with a simple project. A fix should be available on our pre-release channel within the next few days, but in the meantime you should be able to work around the issue by removing double quotes from absolute include paths within STM32CubeIDE.

![image](https://user-images.githubusercontent.com/6981284/192830739-91d79874-2927-405c-8f87-4a104882ae48.png)

**Comment by RaysoftTechnologiesInc** [comment] 2022-09-30 07:02
Hi Ben, 

Thank you for the reply, I had to reset my pc because of some issues, but now I am trying to install and activate vcpkg again, and i am now getting this error.

![image](https://user-images.githubusercontent.com/45296244/193210580-603d64db-ee13-4ab7-ab2a-c4b9e0cc427e.png)


when I run the vcpkg activate command. What maybe be the issue here?

and also my vscode shows this notification.
![image](https://user-images.githubusercontent.com/45296244/193235100-e4f3d56a-0cd9-4f73-b9b7-9b7d625eeb68.png)
how do I make it run in the vcpkg environment

**Comment by benmcmorran** [comment] 2022-09-30 16:50
@BillyONeal any ideas on the `vcpkg activate` issue shown above?

Once it's working, you can run VS Code in a vcpkg environment simply by running `vcpkg activate` followed by `code .` in the terminal. As a workaround, for these projects vcpkg is only used to acquire CMake and Ninja. If you already have these tools installed and available on `PATH` you can safely ignore the warning about vcpkg environments.

**Comment by BillyONeal** [comment] 2022-09-30 16:58
1. Is your `VCPKG_ROOT` set to `C:\Users\Raymond Mango\.vcpkg` ?
2. Does `C:\Users\Raymond Mango\.vcpkg\vcpkg.exe` exist?
3. If you create `C:\Users\Raymond Mango\.vcpkg\node_modules`, does that fix it?

Thanks!

**Comment by RaysoftTechnologiesInc** [comment] 2022-10-03 11:14
Hi Billy,

1) So I have et the VCPKG_ROOT to C:\Users\Raymond Mango\.vcpkg.
2) Yes the .exe file exists.
3) I tried creating it, but running the command vcpkg activate deletes th folder and gives the same error again. i am not sure where I am going wrong because I seemed to get it right the first time. I am regretting restarting my PC.

Is there a link I can follow up the steps of installing the vcpkg from scratch I want to maybe redo everything from scratch.

**Comment by BillyONeal** [comment] 2022-10-03 11:52
@benmcmorran Is there a way to get VS to run vcpkg with `--debug`?

**Comment by benmcmorran** [comment] 2022-10-03 23:26
We don't currently have a way to add additional arguments to the command line invocation, but it looks like OP was running vcpkg in a VS Code integrated terminal, not VS. Would simply running `vcpkg activate --debug` get the information you're looking for?

**Comment by BillyONeal** [comment] 2022-10-04 00:18
I hope!

**Comment by RaysoftTechnologiesInc** [comment] 2022-10-04 09:28
I have run the command  vcpkg activate --debug. this is what I got


![image](https://user-images.githubusercontent.com/45296244/193784896-ac81947d-90e6-491d-8cd3-a8f53895f195.png)

**Comment by benmcmorran** [comment] 2022-10-10 22:11
@BillyONeal do you see anything obvious in the log above?

**Comment by escherstair** [comment] 2022-10-11 06:02
> I am trying to import my ST project into VS Code, I have followed all the steps in the blog I saw on Facebook,

@RaysoftTechnologiesInc can you post the link to the page describing how to import ST project into VS Code?
Thanks

**Comment by benmcmorran** [comment] 2022-10-11 16:17
@escherstair https://devblogs.microsoft.com/cppblog/importing-st-projects-into-visual-studio-code/

**Comment by BillyONeal** [comment] 2022-10-11 23:57
> @BillyONeal do you see anything obvious in the log above?

I do not. This line looks like it got cut off:

![image](https://user-images.githubusercontent.com/1544943/195218934-c2a00b6d-b7f1-43e5-93ed-5243589e9ccd.png)

It looks like we tried to download vcpkg-ce, tried to ask npm to unpack it, and somehow that produced no output but did nothing and returned a success code. We then try to mark that we pulled in the right bits and that explodes because nothing got extracted... I think. But where we would expect a command line to be printed etc. of what we invoked is garbled/missing. As a result I'm not sure how to proceed without repro instructions :(

**Comment by benmcmorran** [comment] 2022-10-14 21:35
A fix for the original issue to correctly handle double quotes around absolute include paths is now available in version 0.4.0 of the Embedded Tools extension, which is available on the VS Code Marketplace. Since the original issue is resolved, I'm going to close this issue, but @RaysoftTechnologiesInc if you're still running into issues with vcpkg on the command line, consider opening an [issue on the vcpkg repo](https://github.com/microsoft/vcpkg/issues) where they should be better equipped to help out.

**Closed by benmcmorran** 2022-10-14 21:35 UTC
Labels: bug
